app = "ecm-atlas"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  DEBUG = "False"
  DATA_PATH = "08_merged_ecm_dataset/merged_ecm_aging_zscore.csv"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[checks]
  [checks.alive]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    expected_http_status = 200
